version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    command: node index.js
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
  db:
    image: rahulpatil1992/myhub:mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
